import ThemeProviders from "@/app/providers/ThemeProviders";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type IRootLayout = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: IRootLayout) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviders>{children}</ThemeProviders>
      </body>
    </html>
  );
};

export default RootLayout;
